openapi: 3.0.0
info:
  version: '1.0'
  title: 'Stent Thrombosis Risk Calculator'
  description: 'This object is derived from the DAPT study that aimed to identify the risk of benefit vs. harm for patients that continue thienopyridine treatment beyond one year after percutaneous coronary intervention (PCI). This object input is a dictionary containing risk values for 12 different risk factors. It will then calculate the estimated risk of MI/stent thrombosis in the 12-30 month period post PCI using the following formula: RISK = 1 - S(18)^exp(sum of [coefficient * risk factor values] - sum). '
servers:
  - url: '/99999/fk45m6gq9t/1.0'
    description: Stent Thrombosis Risk
tags:
  - name: KO Endpoints
    description: Stent Thrombosis Risk Endpoints
paths:
  /getStentThrombosisRisk:
    post:
      tags:
        - KO Endpoints
      description: Stent Thrombosis Risk
      operationId: bleedingrisk
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    input:
      required:
        - DAPT
        - infar
        - priorPCI
        - CHF
        - veinGraft
        - stentDiameter
        - pac
        - cigSmoker
        - diabetes
        - periphDisease
        - hypertension
        - renal
      properties:
        DAPT:
          type: integer
          example: 1
        infar:
          type: integer
          example: 0
        priorPCI:
          type: integer
          example: 0
        CHF:
          type: integer
          example: 1
        veinGraft:
          type: integer
          example: 0
        stentDiameter:
          type: integer
          example: 1
        pac:
          type: integer
          example: 1
        cigSmoker:
          type: integer
          example: 1
        diabetes:
          type: integer
          example: 0
        periphDisease:
          type: integer
          example: 0
        hypertension:
          type: integer
          example: 1
        renal:
          type: integer
          example: 0
    output:
      required:
        - result
      properties:
        result:
          type: string
          example: '0.024'
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
